steps:
  gctsExecuteABAPUnitTests:
    host: 'http://63.32.62.246:8200'
    client: '100'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'leonburkhardt-gcts_test'
    verbose: true
